import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, test } from 'vitest'
import type { CodegenError } from '../src/errors.js'
import { generate, outputPrefix } from '../src/generate.js'

let workspace = ''

beforeEach(async () => {
  workspace = await mkdtemp(path.join(tmpdir(), 'feat2test-'))
})

afterEach(async () => {
  await rm(workspace, { recursive: true, force: true })
})

/** Writes a Feature and generates from it, returning both outputs. */
async function run(
  source: string,
  { filename = 'shop.feature.md', check = false } = {},
): Promise<{ steps: string; test: string; warnings: readonly string[] }> {
  const input = path.join(workspace, filename)
  await writeFile(input, source, 'utf8')
  const report = await generate(input, workspace, { check, runner: 'vitest' })
  return {
    steps: await read(report.stepAdapterPath),
    test: await read(report.testPath),
    warnings: report.warnings,
  }
}

async function read(target: string): Promise<string> {
  return await readFile(target, 'utf8').catch(() => '')
}

async function failure(source: string, filename = 'shop.feature.md'): Promise<CodegenError> {
  const input = path.join(workspace, filename)
  await writeFile(input, source, 'utf8')
  try {
    await generate(input, workspace, { runner: 'vitest' })
  } catch (error) {
    return error as CodegenError
  }
  throw new Error('expected generation to fail')
}

const MINIMAL = `# Feature: Shop

## Scenario: Browse

* Given the shop is open
* When the customer browses
* Then products are listed
`

describe('output naming', () => {
  test.each([
    ['customer.feature', 'customer.feature'],
    ['customer.feature.md', 'customer.feature'],
    ['customer.txt', 'customer.feature'],
    ['customer.spec.md', 'customer.spec.feature'],
    ['customer', 'customer.feature'],
  ])('%s becomes %s', (filename, expected) => {
    expect(outputPrefix(filename)).toBe(expected)
  })
})

describe('the Feature Test', () => {
  test('mirrors the scenario as a Vitest test with commented steps', async () => {
    const { test: generated } = await run(MINIMAL)

    expect(generated).toBe(`// Generated by feat2test. Do not edit.
import { describe, test } from 'vitest'
import { createSteps } from './shop.feature.steps.js'

describe('Feature: Shop', () => {
  // Line 3
  test('Browse', async () => {
    const steps = createSteps()

    // Given the shop is open
    await steps.theShopIsOpen()
    // When the customer browses
    await steps.theCustomerBrowses()
    // Then products are listed
    await steps.productsAreListed()
  })
})
`)
  })

  test('nests scenarios of a Rule in their own describe', async () => {
    const { test: generated } = await run(`# Feature: Shop

## Rule: Stock limits the cart

### Scenario: Add a stocked product

* When the customer adds a stocked product
* Then the cart holds it
`)

    expect(generated).toContain(`describe('Rule: Stock limits the cart', () => {`)
    expect(generated).toContain(`    test('Add a stocked product', async () => {`)
  })

  test('inlines Background steps into every scenario', async () => {
    const { test: generated } = await run(`# Feature: Shop

## Background:

* Given the shop is open

## Scenario: Browse

* When the customer browses
* Then products are listed
`)

    expect(generated).toContain('await steps.theShopIsOpen()')
  })

  test('passes each Examples row as its own test', async () => {
    const { test: generated } = await run(`# Feature: Shop

## Scenario Outline: Add <quantity> units

* When the customer adds \`<quantity>\` units
* Then the cart holds \`<quantity>\` units

#### Examples:

  | quantity |
  | 1 |
  | 9 |
`)

    expect(generated).toContain(`test('Add 1 units', async () => {`)
    expect(generated).toContain(`test('Add 9 units', async () => {`)
    expect(generated).toContain(`await steps.theCustomerAddsUnits('9')`)
  })

  test('disambiguates repeated scenario names', async () => {
    const { test: generated } = await run(`# Feature: Shop

## Scenario Outline: Add units

* When the customer adds \`<quantity>\` units
* Then the cart is updated

#### Examples:

  | quantity |
  | 1 |
  | 9 |
`)

    expect(generated).toContain(`test('Add units', async () => {`)
    expect(generated).toContain(`test('Add units #2', async () => {`)
  })

  test('passes a DataTable as a string matrix', async () => {
    const { test: generated } = await run(`# Feature: Shop

## Scenario: Order two products

* Given the order contains:
  | product | quantity |
  | Pencil | 2 |
  | Notebook | 1 |
* Then the order holds two lines
`)

    expect(generated).toContain(`    await steps.theOrderContains([
      ['product', 'quantity'],
      ['Pencil', '2'],
      ['Notebook', '1'],
    ])`)
  })

  test('passes a DocString as text', async () => {
    const { test: generated } = await run(`# Feature: Shop

## Scenario: Publish a notice

* When the shop publishes:
  \`\`\`
  Closed today
  \`\`\`
* Then the notice is visible
`)

    expect(generated).toContain(`await steps.theShopPublishes('Closed today')`)
  })

  test('escapes quotes and backslashes in generated literals', async () => {
    const { test: generated } = await run(`# Feature: Shop

## Scenario Outline: Show <label>

* Then the label shows \`<label>\`

#### Examples:

  | label |
  | it's a \\\\ break |
`)

    expect(generated).toContain(`await steps.theLabelShows('it\\'s a \\\\ break')`)
  })

  test('is rewritten whenever the Feature changes', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL, 'utf8')
    const first = await generate(input, workspace, { runner: 'vitest' })

    await writeFile(input, MINIMAL.replace('Browse', 'Search'), 'utf8')
    await generate(input, workspace, { runner: 'vitest' })

    expect(await read(first.testPath)).toContain(`test('Search'`)
  })

  test('refuses to replace a file it did not generate', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL, 'utf8')
    await writeFile(path.join(workspace, 'shop.feature.test.ts'), 'handwritten', 'utf8')

    await expect(generate(input, workspace, { runner: 'vitest' })).rejects.toMatchObject({
      code: 'OUTPUT_CONFLICT',
    })
  })
})

describe('the Step Adapter', () => {
  test('scaffolds one pending method per distinct step, grouped by role', async () => {
    const { steps } = await run(MINIMAL)

    expect(steps).toBe(`// Scaffolded by feat2test. Yours to edit: it is never overwritten.

export function createSteps() {
  return {
    // Context
    theShopIsOpen(): void {
      throw new Error('PENDING: theShopIsOpen')
    },

    // Action
    theCustomerBrowses(): void {
      throw new Error('PENDING: theCustomerBrowses')
    },

    // Outcome
    productsAreListed(): void {
      throw new Error('PENDING: productsAreListed')
    },
  }
}
`)
  })

  test('declares one plain parameter per placeholder', async () => {
    const { steps } = await run(`# Feature: Shop

## Scenario Outline: Format <value>

* When value \`<value>\` is formatted for language \`<language>\`
* Then display shows \`<formatted>\`

#### Examples:

  | value | language | formatted |
  | 1234.56 | Spanish | 1.234,56 |
`)

    expect(steps).toContain('valueIsFormattedForLanguage(value: string, language: string): void {')
    expect(steps).toContain('displayShows(formatted: string): void {')
  })

  test('keeps the camelCase of a placeholder name', async () => {
    const { steps } = await run(`# Feature: Shop

## Scenario Outline: Reject <unavailableProduct>

* When the customer orders \`<unavailableProduct>\`
* Then the order is rejected

#### Examples:

  | unavailableProduct |
  | Notebook |
`)

    expect(steps).toContain('theCustomerOrders(unavailableProduct: string): void {')
  })

  test('types a DataTable step as a string matrix', async () => {
    const { steps } = await run(`# Feature: Shop

## Scenario: Order products

* Given the order contains:
  | product |
  | Pencil |
* Then the order holds one line
`)

    expect(steps).toContain('theOrderContains(table: string[][]): void {')
  })

  test('is never overwritten once it exists', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL, 'utf8')
    const first = await generate(input, workspace, { runner: 'vitest' })
    await writeFile(first.stepAdapterPath, '// mine\nexport function createSteps() {}\n', 'utf8')

    await writeFile(input, MINIMAL.replace('the shop is open', 'the shop is closed'), 'utf8')
    const second = await generate(input, workspace, { runner: 'vitest' })

    expect(await read(second.stepAdapterPath)).toBe('// mine\nexport function createSteps() {}\n')
    expect(second.stepAdapterWritten).toBe(false)
  })
})

describe('step identity', () => {
  test('shares one method between steps with the same literal words', async () => {
    const { steps } = await run(`# Feature: Shop

## Scenario Outline: Add <quantity>

* When the customer adds \`<quantity>\` units
* And the customer adds \`<quantity>\` units
* Then the cart is updated

#### Examples:

  | quantity |
  | 2 |
`)

    expect(steps.match(/theCustomerAddsUnits/g)).toHaveLength(2)
  })

  test('rejects one wording used as both Context and Outcome', async () => {
    const error = await failure(`# Feature: Shop

## Scenario: Confuse roles

* Given the cart is empty
* When the customer browses
* Then the cart is empty
`)

    expect(error.code).toBe('CONFLICTING_STEP_ROLE')
  })

  test('rejects one wording used with different inputs', async () => {
    const error = await failure(`# Feature: Shop

## Scenario Outline: Add <quantity>

* When the customer adds units
* And the customer adds \`<quantity>\` units
* Then the cart is updated

#### Examples:

  | quantity |
  | 2 |
`)

    expect(error.code).toBe('CONFLICTING_STEP_INPUTS')
  })

  test('keeps a reserved word from becoming an identifier', async () => {
    const { steps } = await run(`# Feature: Shop

## Scenario: Return

* When return
* Then the cart is updated
`)

    expect(steps).toContain('returnStep(): void {')
  })
})

describe('input validation', () => {
  test('reports a missing input file', async () => {
    await expect(
      generate(path.join(workspace, 'absent.md'), workspace, { runner: 'vitest' }),
    ).rejects.toMatchObject({
      code: 'INPUT_UNREADABLE',
    })
  })

  test('reports a Feature without a name', async () => {
    const error = await failure('# Scenario: Orphan\n\n* When nothing happens\n')

    expect(error.code).toBe('INVALID_GHERKIN')
  })

  test('reports a Feature without runnable scenarios', async () => {
    const error = await failure('# Feature: Shop\n\nJust prose.\n')

    expect(error.code).toBe('INVALID_GHERKIN')
  })

  test('reports classic Gherkin syntax errors', async () => {
    const error = await failure(
      'Feature: Shop\n  Scenario: Browse\n    Given x\n  Background:\n    Given y\n',
      'shop.feature',
    )

    expect(error.code).toBe('INVALID_GHERKIN')
    expect(error.message).toContain('expected:')
  })

  test('reports a placeholder that no Examples column provides', async () => {
    const error = await failure(`# Feature: Shop

## Scenario Outline: Add units

* When the customer adds \`<quantity>\` units
* Then the cart is updated

#### Examples:

  | amount |
  | 2 |
`)

    expect(error.code).toBe('UNKNOWN_PLACEHOLDER')
  })
})

describe('classic Gherkin', () => {
  test('parses a .feature file and its language header', async () => {
    const { test: generated } = await run(
      `# language: es
Característica: Tienda

  Escenario: Navegar

    Dado que la tienda está abierta
    Cuando el cliente navega
    Entonces se listan los productos
`,
      { filename: 'tienda.feature' },
    )

    expect(generated).toContain(`describe('Feature: Tienda', () => {`)
    expect(generated).toContain('await steps.queLaTiendaEstaAbierta()')
  })
})

describe('warnings', () => {
  test('flags a Markdown separator row that Cucumber reads as data', async () => {
    const { warnings } = await run(`# Feature: Shop

## Scenario Outline: Add <quantity>

* When the customer adds \`<quantity>\` units
* Then the cart is updated

#### Examples:

  | quantity |
  | --- |
  | 2 |
`)

    expect(warnings.join('\n')).toContain('Markdown separator row')
  })

  test('flags a Markdown table row indented by fewer than two spaces', async () => {
    const { warnings } = await run(`# Feature: Shop

## Scenario: Order products

* Given the order contains:
 | product |
 | Pencil |
* Then the order holds one line
`)

    expect(warnings.join('\n')).toContain('two leading spaces')
  })
})

describe('--check', () => {
  test('passes when both outputs are current', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL, 'utf8')
    await generate(input, workspace, { runner: 'vitest' })

    await expect(
      generate(input, workspace, { check: true, runner: 'vitest' }),
    ).resolves.toMatchObject({
      scenarioCount: 1,
    })
  })

  test('fails when the Feature Test is stale', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL, 'utf8')
    await generate(input, workspace, { runner: 'vitest' })
    await writeFile(input, MINIMAL.replace('Browse', 'Search'), 'utf8')

    await expect(
      generate(input, workspace, { check: true, runner: 'vitest' }),
    ).rejects.toMatchObject({
      code: 'CHECK_FAILED',
    })
  })

  test('fails when the Step Adapter is missing', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL, 'utf8')

    await expect(
      generate(input, workspace, { check: true, runner: 'vitest' }),
    ).rejects.toMatchObject({
      code: 'CHECK_FAILED',
    })
  })

  test('writes nothing', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL, 'utf8')

    await generate(input, workspace, { check: true, runner: 'vitest' }).catch(() => undefined)

    expect(await read(path.join(workspace, 'shop.feature.test.ts'))).toBe('')
  })
})

describe('runners and migration', () => {
  test('switches runner while preserving user code and detects runner drift', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL)
    const first = await generate(input, workspace, { runner: 'vitest' })
    await writeFile(first.stepAdapterPath, '// User-owned implementation\n')
    await expect(
      generate(input, workspace, { runner: 'node:test', check: true }),
    ).rejects.toMatchObject({ code: 'CHECK_FAILED' })
    await generate(input, workspace, { runner: 'node:test' })
    const output = await read(first.testPath)
    expect(output).toContain("from 'node:test'")
    expect(output).toContain("from './shop.feature.steps.ts'")
    expect(output).not.toContain('vitest')
    expect(await read(first.stepAdapterPath)).toBe('// User-owned implementation\n')
    await expect(
      generate(input, workspace, { runner: 'node:test', check: true }),
    ).resolves.toMatchObject({ scenarioCount: 1 })
  })

  test('migrates the legacy ownership header without touching the adapter', async () => {
    const input = path.join(workspace, 'shop.feature.md')
    await writeFile(input, MINIMAL)
    const first = await generate(input, workspace, { runner: 'vitest' })
    await writeFile(
      first.testPath,
      '// Generated by gherkin-vitest-codegen. Do not edit.\n// Old output\n',
    )
    const adapter = await read(first.stepAdapterPath)
    await generate(input, workspace, { runner: 'vitest' })
    expect(await read(first.testPath)).toMatch(/^\/\/ Generated by feat2test\./)
    expect(await read(first.stepAdapterPath)).toBe(adapter)
  })

  test('escapes an adapter import when the input filename contains a quote', async () => {
    const { test: output } = await run(MINIMAL, { filename: "shop's.feature.md" })
    expect(output).toContain("from './shop\\'s.feature.steps.js'")
  })
})
