// Generated by yarn run:example from a standalone feature.
import { defineConfig, definePack } from '../../src/index.ts'

const taskList = definePack({
  id: 'taskList',
  factory: 'taskListSteps',
  importPath: './test/steps/task-list.steps.ts',
})

taskList
  .step(/^an empty task list$/, () => ({ method: 'anEmptyTaskList' }))
  .step(/^the user adds "([^"]*)"$/, ({ captures }) => ({
    method: 'theUserAdds',
    args: [required(captures[0])],
  }))
  .step(/^the task list contains "([^"]*)"$/, ({ captures }) => ({
    method: 'theTaskListContains',
    args: [required(captures[0])],
  }))
  .step(/^the user adds "([^"]*)" with priority "([^"]*)"$/, ({ captures }) => ({
    method: 'theUserAddsWithPriority',
    args: [required(captures[0]), required(captures[1])],
  }))
  .step(/^the task list contains "([^"]*)" with priority "([^"]*)"$/, ({ captures }) => ({
    method: 'theTaskListContainsWithPriority',
    args: [required(captures[0]), required(captures[1])],
  }))
  .step(/^the user added "([^"]*)"$/, ({ captures }) => ({
    method: 'theUserAdded',
    args: [required(captures[0])],
  }))
  .step(/^the user completes "([^"]*)"$/, ({ captures }) => ({
    method: 'theUserCompletes',
    args: [required(captures[0])],
  }))
  .step(/^"([^"]*)" is marked as completed$/, ({ captures }) => ({
    method: 'isMarkedAsCompleted',
    args: [required(captures[0])],
  }))

export default defineConfig({
  featureRoot: '.',
  features: ['task-list.feature.md'],
  packs: [taskList],
})

function required(value: string | undefined): string {
  if (value === undefined) throw new Error('Expected a regex capture.')
  return value
}
