import { existsSync } from 'node:fs'
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { GherkinDocument, Step } from '@cucumber/messages'
import { glob } from 'glob'
import { CONFIG_FILENAMES, loadConfig, resolveConfig } from '../src/config.js'
import { generate } from '../src/generate.js'
import { loadFeature } from '../src/gherkin.js'
import { definePack } from '../src/pack.js'
import type { GenerationReport, ResolvedCodegenConfig } from '../src/types.js'

const GENERATED_CONFIG_MARKER = '// Generated by yarn run:example from a standalone feature.'
const repositoryRoot = fileURLToPath(new URL('../', import.meta.url))
const featurePatterns = ['**/*.feature', '**/*.feature.md']
const reservedIdentifiers = new Set([
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'interface',
  'let',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
])

export interface ExampleCompilation {
  readonly artifactPaths: readonly string[]
  readonly report: GenerationReport
}

interface ExampleNames {
  readonly factory: string
  readonly instance: string
  readonly slug: string
}

interface StepPlan {
  readonly captureNames: readonly string[]
  readonly keyword: string
  readonly method: string
  readonly pattern: string
  readonly text: string
}

export async function compileExample(
  inputPath: string,
  cwd = process.cwd(),
): Promise<ExampleCompilation> {
  const absoluteInput = path.resolve(cwd, inputPath)
  const input = await inputStats(absoluteInput)
  const searchDirectory = input.isDirectory() ? absoluteInput : path.dirname(absoluteInput)
  if (!input.isDirectory()) assertFeaturePath(absoluteInput)

  const existingConfig = findConfigUp(searchDirectory)
  if (existingConfig && !(await isGeneratedConfig(existingConfig))) {
    const loaded = await loadConfig({ configPath: existingConfig })
    const report = await generate(loaded.config)
    return {
      artifactPaths: [existingConfig, ...report.files.map((file) => file.outputPath)],
      report,
    }
  }

  const rootDir = existingConfig ? path.dirname(existingConfig) : searchDirectory
  const featurePath = await findStandaloneFeature(absoluteInput, input.isDirectory(), rootDir)
  const scaffold = await scaffoldExample(rootDir, featurePath)
  const report = await generate(scaffold.configValue)

  return {
    artifactPaths: [
      scaffold.configPath,
      scaffold.stepsPath,
      ...report.files.map((file) => file.outputPath),
    ],
    report,
  }
}

async function scaffoldExample(
  rootDir: string,
  featurePath: string,
): Promise<{
  readonly configPath: string
  readonly configValue: ResolvedCodegenConfig
  readonly stepsPath: string
}> {
  const feature = await loadFeature(featurePath, rootDir, 'en')
  const names = namesFor(featurePath)
  const plans = planSteps(feature.document)
  const configPath = path.join(rootDir, 'gherkin-vitest.config.ts')
  const stepsPath = path.join(rootDir, 'test/steps', `${names.slug}.steps.ts`)

  await mkdir(path.dirname(stepsPath), { recursive: true })
  await writeFile(configPath, renderConfig(configPath, featurePath, rootDir, names, plans), 'utf8')
  if (!existsSync(stepsPath)) {
    await writeFile(stepsPath, renderStepScaffold(names, plans), 'utf8')
  }

  const pack = definePack({
    id: names.instance,
    factory: names.factory,
    importPath: `./test/steps/${names.slug}.steps.ts`,
  })
  for (const plan of plans) {
    pack.step(new RegExp(plan.pattern), ({ captures }) => ({
      method: plan.method,
      ...(plan.captureNames.length > 0
        ? { args: plan.captureNames.map((_, index) => required(captures[index])) }
        : {}),
    }))
  }

  const relativeFeature = slash(path.relative(rootDir, featurePath))
  return {
    configPath,
    configValue: resolveConfig({
      rootDir,
      featureRoot: slash(path.dirname(relativeFeature)),
      features: [relativeFeature],
      packs: [pack],
    }),
    stepsPath,
  }
}

function renderConfig(
  configPath: string,
  featurePath: string,
  rootDir: string,
  names: ExampleNames,
  plans: readonly StepPlan[],
): string {
  const apiPath = modulePath(configPath, path.join(repositoryRoot, 'src/index.ts'))
  const relativeFeature = slash(path.relative(rootDir, featurePath))
  const featureRoot = slash(path.dirname(relativeFeature))
  const definitions = plans.map(renderDefinition).join('\n')
  const needsRequired = plans.some((plan) => plan.captureNames.length > 0)

  return [
    GENERATED_CONFIG_MARKER,
    `import { defineConfig, definePack } from '${apiPath}'`,
    '',
    `const ${names.instance} = definePack({`,
    `  id: '${names.instance}',`,
    `  factory: '${names.factory}',`,
    `  importPath: './test/steps/${names.slug}.steps.ts',`,
    '})',
    '',
    names.instance,
    definitions,
    '',
    'export default defineConfig({',
    `  featureRoot: '${featureRoot}',`,
    `  features: ['${escapeString(relativeFeature)}'],`,
    `  packs: [${names.instance}],`,
    '})',
    ...(needsRequired
      ? [
          '',
          'function required(value: string | undefined): string {',
          "  if (value === undefined) throw new Error('Expected a regex capture.')",
          '  return value',
          '}',
        ]
      : []),
    '',
  ].join('\n')
}

function renderDefinition(plan: StepPlan): string {
  if (plan.captureNames.length === 0) {
    return `  .step(/${plan.pattern}/, () => ({ method: '${plan.method}' }))`
  }
  const args = plan.captureNames.map((_, index) => `required(captures[${index}])`).join(', ')
  return [
    `  .step(/${plan.pattern}/, ({ captures }) => ({`,
    `    method: '${plan.method}',`,
    `    args: [${args}],`,
    '  }))',
  ].join('\n')
}

function renderStepScaffold(names: ExampleNames, plans: readonly StepPlan[]): string {
  const methods = plans
    .map((plan) => {
      const parameters = plan.captureNames.map((name) => `${name}: string`).join(', ')
      const unused = plan.captureNames.map((name) => `      void ${name}`)
      return [
        `    ${plan.method}(${parameters}): void {`,
        ...unused,
        `      throw new Error('${escapeString(`TODO: ${plan.keyword} ${plan.text}`)}')`,
        '    },',
      ].join('\n')
    })
    .join('\n')

  return [
    '// Scaffolded by yarn run:example. Implement these test adapters during TDD.',
    `export function ${names.factory}() {`,
    '  return {',
    methods,
    '  }',
    '}',
    '',
  ].join('\n')
}

function planSteps(document: GherkinDocument): StepPlan[] {
  const plans: StepPlan[] = []
  const patterns = new Set<string>()
  const methods = new Set<string>()

  for (const step of sourceSteps(document)) {
    const parsed = parsePattern(step.text)
    if (patterns.has(parsed.pattern)) continue
    patterns.add(parsed.pattern)

    const baseMethod = methodName(step.text)
    let method = baseMethod
    let suffix = 2
    while (methods.has(method)) {
      method = `${baseMethod}${suffix}`
      suffix += 1
    }
    methods.add(method)
    plans.push({
      captureNames: parsed.captureNames,
      keyword: step.keyword.trim(),
      method,
      pattern: parsed.pattern,
      text: step.text,
    })
  }

  return plans
}

function sourceSteps(document: GherkinDocument): Step[] {
  const result: Step[] = []
  const feature = document.feature
  if (!feature) return result

  for (const child of feature.children) {
    if (child.background) result.push(...child.background.steps)
    if (child.scenario) result.push(...child.scenario.steps)
    if (child.rule) {
      for (const ruleChild of child.rule.children) {
        if (ruleChild.background) result.push(...ruleChild.background.steps)
        if (ruleChild.scenario) result.push(...ruleChild.scenario.steps)
      }
    }
  }
  return result
}

function parsePattern(text: string): { readonly captureNames: string[]; readonly pattern: string } {
  const captures: string[] = []
  const dynamic = /"([^"]*)"|<([^>]+)>/g
  let pattern = '^'
  let cursor = 0

  for (const match of text.matchAll(dynamic)) {
    pattern += escapeRegex(text.slice(cursor, match.index))
    const quoted = match[1] !== undefined
    const value = quoted ? match[1] : match[2]
    const quotedPlaceholder = quoted ? value?.match(/^<([^>]+)>$/)?.[1] : undefined
    const captureName = quoted ? placeholderName(quotedPlaceholder) : placeholderName(value)
    captures.push(uniqueCaptureName(captures, captureName))
    pattern += quoted ? '"([^"]*)"' : '(.+)'
    cursor = match.index + match[0].length
  }

  pattern += `${escapeRegex(text.slice(cursor))}$`
  return { captureNames: captures, pattern }
}

function methodName(text: string): string {
  const literalWords = text.replaceAll(/"[^"]*"|<[^>]+>/g, ' ')
  const words = asciiWords(literalWords)
  if (words.length === 0) return 'step'
  const [first, ...rest] = words
  return safeIdentifier(`${required(first).toLowerCase()}${rest.map(capitalize).join('')}`, 'step')
}

function placeholderName(value: string | undefined): string {
  const placeholder = value?.match(/^<([^>]+)>$/)?.[1] ?? value
  const words = asciiWords(placeholder ?? '')
  if (words.length === 0) return 'value'
  const [first, ...rest] = words
  return safeIdentifier(`${required(first).toLowerCase()}${rest.map(capitalize).join('')}`, 'value')
}

function uniqueCaptureName(existing: readonly string[], base: string): string {
  let name = base
  let suffix = 2
  while (existing.includes(name)) {
    name = `${base}${suffix}`
    suffix += 1
  }
  return name
}

function namesFor(featurePath: string): ExampleNames {
  const stem = path.basename(featurePath).replace(/\.feature(?:\.md)?$/, '')
  const words = asciiWords(stem)
  const fallbackWords = words.length > 0 ? words : ['example']
  const instance = safeIdentifier(
    `${required(fallbackWords[0]).toLowerCase()}${fallbackWords.slice(1).map(capitalize).join('')}`,
    'example',
  )
  return {
    factory: `${instance}Steps`,
    instance,
    slug: fallbackWords.map((word) => word.toLowerCase()).join('-'),
  }
}

async function findStandaloneFeature(
  absoluteInput: string,
  inputIsDirectory: boolean,
  rootDir: string,
): Promise<string> {
  const matches = await glob(featurePatterns, { cwd: rootDir, absolute: true, nodir: true })
  const features = [...new Set(matches.map((value) => path.resolve(value)))].sort()
  if (features.length === 0) throw new Error(`No .feature or .feature.md file found in ${rootDir}.`)
  if (features.length > 1) {
    throw new Error(`Expected one feature in ${rootDir}; found ${features.length}.`)
  }
  if (!inputIsDirectory && features[0] !== absoluteInput) {
    throw new Error(`Expected ${absoluteInput} to be the only feature in ${rootDir}.`)
  }
  return required(features[0])
}

async function inputStats(absoluteInput: string) {
  try {
    const result = await stat(absoluteInput)
    if (!result.isDirectory() && !result.isFile()) {
      throw new Error(`Example path must be a file or directory: ${absoluteInput}`)
    }
    return result
  } catch (error) {
    if (isMissing(error)) throw new Error(`Example path not found: ${absoluteInput}`)
    throw error
  }
}

async function isGeneratedConfig(configPath: string): Promise<boolean> {
  return (await readFile(configPath, 'utf8')).startsWith(GENERATED_CONFIG_MARKER)
}

function assertFeaturePath(value: string): void {
  if (!value.endsWith('.feature') && !value.endsWith('.feature.md')) {
    throw new Error(`Example file must end in .feature or .feature.md: ${value}`)
  }
}

function findConfigUp(start: string): string | undefined {
  let directory = start
  while (true) {
    for (const filename of CONFIG_FILENAMES) {
      const candidate = path.join(directory, filename)
      if (existsSync(candidate)) return candidate
    }
    const parent = path.dirname(directory)
    if (parent === directory) return undefined
    directory = parent
  }
}

function modulePath(fromFile: string, targetFile: string): string {
  let relative = slash(path.relative(path.dirname(fromFile), targetFile))
  if (!relative.startsWith('.')) relative = `./${relative}`
  return relative
}

function asciiWords(value: string): string[] {
  return (
    value
      .normalize('NFKD')
      .replaceAll(/\p{Diacritic}/gu, '')
      .match(/[A-Za-z0-9]+/g) ?? []
  )
}

function capitalize(value: string): string {
  return `${value.charAt(0).toUpperCase()}${value.slice(1).toLowerCase()}`
}

function safeIdentifier(value: string, fallback: string): string {
  const candidate = /^[$A-Z_a-z]/.test(value) ? value : `${fallback}${capitalize(value)}`
  return reservedIdentifiers.has(candidate) ? `${candidate}${capitalize(fallback)}` : candidate
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')
}

function escapeString(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n')
}

function isMissing(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error && error.code === 'ENOENT'
}

function required<T>(value: T | undefined): T {
  if (value === undefined) throw new Error('Expected value.')
  return value
}

function slash(value: string): string {
  return value.replaceAll(path.sep, '/')
}
