import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { CodegenError } from './errors.js'
import { parseFeature } from './parse.js'
import { planFeature } from './plan.js'
import { GENERATED_HEADER } from './render.js'
import { type RunnerName, resolveRunner } from './runners.js'
import { renderStepAdapter } from './steps.js'
import { synchronizeStepAdapter } from './sync-steps.js'
import type { GenerationReport } from './types.js'

export interface GenerateOptions {
  readonly runner: RunnerName
  readonly check?: boolean
}

/**
 * Feature in, two synchronized files out. Existing step implementations survive
 * while their signatures still occur in the Feature.
 */
export async function generate(
  inputPath: string,
  outputDirectory: string,
  options: GenerateOptions,
): Promise<GenerationReport> {
  const runner = resolveRunner(options.runner)
  const input = path.resolve(inputPath)
  const output = path.resolve(outputDirectory)
  const label = display(input)

  const prefix = outputPrefix(path.basename(input))
  const testPath = path.join(output, `${prefix}.test.ts`)
  const stepAdapterPath = path.join(output, `${prefix}.steps.ts`)

  const parsed = await parseFeature(input, label)
  const plan = planFeature(parsed, label)
  const test = runner.render(plan, `./${prefix}.steps`)
  const currentStepAdapter = await read(stepAdapterPath)
  const stepAdapter =
    currentStepAdapter === undefined
      ? renderStepAdapter(plan)
      : synchronizeStepAdapter(plan, currentStepAdapter, display(stepAdapterPath))
  const stepAdapterChanged = currentStepAdapter !== stepAdapter

  if (options.check) {
    const problems: string[] = []
    if ((await read(testPath)) !== test) problems.push(`out of date: ${display(testPath)}`)
    if (currentStepAdapter === undefined) problems.push(`missing: ${display(stepAdapterPath)}`)
    else if (stepAdapterChanged) problems.push(`out of date: ${display(stepAdapterPath)}`)
    if (problems.length > 0) {
      throw new CodegenError('CHECK_FAILED', `Regenerate this Feature:\n${problems.join('\n')}`)
    }
  } else {
    await mkdir(output, { recursive: true })
    await writeGenerated(testPath, test)
    if (stepAdapterChanged) {
      await writeFile(stepAdapterPath, stepAdapter, {
        encoding: 'utf8',
        flag: currentStepAdapter === undefined ? 'wx' : 'w',
      })
    }
  }

  return {
    scenarioCount: plan.scenarios.length,
    stepAdapterPath,
    stepAdapterWritten: !options.check && stepAdapterChanged,
    stepCount: plan.steps.length,
    testPath,
    warnings: parsed.warnings,
  }
}

/** Everything before the last extension, guaranteed to end in `.feature`. */
export function outputPrefix(filename: string): string {
  const extension = path.extname(filename)
  const stem = extension ? filename.slice(0, -extension.length) : filename
  return stem.endsWith('.feature') ? stem : `${stem}.feature`
}

/** Refuse to replace a file the generator did not write. */
async function writeGenerated(target: string, contents: string): Promise<void> {
  const current = await read(target)
  // Accept the previous ownership marker so existing projects can migrate safely.
  const legacyHeader = '// Generated by gherkin-vitest-codegen. Do not edit.'
  if (
    current !== undefined &&
    !current.startsWith(GENERATED_HEADER) &&
    !current.startsWith(legacyHeader)
  ) {
    throw new CodegenError(
      'OUTPUT_CONFLICT',
      `${display(target)} was not generated by this tool. Move it aside first.`,
    )
  }
  if (current !== contents) await writeFile(target, contents, 'utf8')
}

async function read(target: string): Promise<string | undefined> {
  try {
    return await readFile(target, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    return undefined
  }
}

function display(target: string): string {
  return path.relative(process.cwd(), target) || path.basename(target)
}
