import type { FeaturePlan, PlannedScenario, StepValue } from './types.js'

export const GENERATED_HEADER = '// Generated by feat2test. Do not edit.'

/** The Feature Test is owned by the generator and rewritten on every run. */
export function renderTest(
  plan: FeaturePlan,
  stepAdapterImport: string,
  runnerImport: string,
): string {
  const blocks: string[] = []
  for (const group of groupByRule(plan.scenarios)) {
    const tests = group.scenarios.map((scenario) => renderScenario(scenario, group.rule ? 2 : 1))
    blocks.push(
      group.rule === undefined
        ? tests.join('\n\n')
        : `  describe('Rule: ${quote(group.rule)}', () => {\n${tests.join('\n\n')}\n  })`,
    )
  }

  return [
    GENERATED_HEADER,
    `import { describe, test } from '${quote(runnerImport)}'`,
    `import { createSteps } from '${quote(stepAdapterImport)}'`,
    '',
    `describe('Feature: ${quote(plan.name)}', () => {`,
    blocks.join('\n\n'),
    '})',
    '',
  ].join('\n')
}

function groupByRule(
  scenarios: readonly PlannedScenario[],
): { rule?: string; scenarios: PlannedScenario[] }[] {
  const groups: { rule?: string; scenarios: PlannedScenario[] }[] = []
  for (const scenario of scenarios) {
    const last = groups.at(-1)
    if (last && last.rule === scenario.rule) last.scenarios.push(scenario)
    else groups.push({ ...(scenario.rule ? { rule: scenario.rule } : {}), scenarios: [scenario] })
  }
  return groups
}

function renderScenario(scenario: PlannedScenario, depth: number): string {
  const pad = '  '.repeat(depth)
  const body = scenario.calls.flatMap((call) => [
    `${pad}  // ${call.keyword} ${call.text}`,
    `${pad}  await steps.${call.method}(${call.values.map((value) => literal(value, `${pad}  `)).join(', ')})`,
  ])
  return [
    `${pad}// Line ${scenario.line}`,
    `${pad}test('${quote(scenario.name)}', async () => {`,
    `${pad}  const steps = createSteps()`,
    '',
    ...body,
    `${pad}})`,
  ].join('\n')
}

function literal(value: StepValue, pad: string): string {
  if (typeof value === 'string') return quoted(value)
  if (value.length === 0) return '[]'
  const rows = value.map((row) => `${pad}  [${row.map(quoted).join(', ')}],`)
  return `[\n${rows.join('\n')}\n${pad}]`
}

function quoted(value: string): string {
  return `'${quote(value)}'`
}

function quote(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('\n', '\\n')
}
